name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y inkscape
      - name: Build project
        run: make
      - name: Build examples
        run: make examples
      - uses: actions/upload-artifact@v3
        with:
          path: |
            debexec_*.deb
            *.dxe
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: version
        run: echo "::set-output name=version::$(./version.sh)"
      - name: Create release
        uses: actions/create-release@v1
        id: create-release
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: ./
      - name: Upload Debian package
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./debexec_${{ steps.version.outputs.version }}_amd64.deb
          asset_name: debexec_${{ steps.version.outputs.version }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: Upload firefox example
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./firefox.dxe
          asset_name: firefox.dxe
          asset_content_type: application/x-debian-executable
      - name: Upload gimp example
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./gimp.dxe
          asset_name: gimp.dxe
          asset_content_type: application/x-debian-executable
      - name: Upload inkscape example
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./inkscape.dxe
          asset_name: inkscape.dxe
          asset_content_type: application/x-debian-executable
      - name: Upload spotify example
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./spotify.dxe
          asset_name: spotify.dxe
          asset_content_type: application/x-debian-executable
